config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matbun/mlpf-itwinai-plugin:
      branch: main
      repo: https://github.com/matbun/mlpf-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matbun/mlpf-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-magenta-ostrich.sh
        container: qc.acc_breezy-olive-kudu
  QC.Doc:
    repos:
      github.com/matbun/mlpf-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-amaranth-mule.sh
        container: qc.doc_leaky-pumpkin-neanderthal
      github.com/matbun/mlpf-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-heliotrope-opossum.sh
        container: qc.doc_shabby-orchid-chicken
      github.com/matbun/mlpf-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bronze-vulture.sh
        container: qc.doc_craggy-emerald-fox
  QC.Lic:
    repos:
      github.com/matbun/mlpf-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-harlequin-burmese.sh
        container: qc.lic_gloppy-teal-bullfrog
  QC.Met:
    repos:
      github.com/matbun/mlpf-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-khaki-dodo.sh
        container: qc.met_seedy-chartreuse-moorhen
  QC.Sec:
    repos:
      github.com/matbun/mlpf-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-thistle-labradoodle.sh
        container: qc.sec_goopy-lilac-dachshund
  QC.Sty:
    repos:
      github.com/matbun/mlpf-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-amber-cougar.sh
        container: qc.sty_boozy-peach-mastiff
      github.com/matbun/mlpf-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cinnabar-beetle.sh
        container: qc.sty_bluesy-gamboge-cockroach
      github.com/matbun/mlpf-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-jade-tarantula.sh
        container: qc.sty_foggy-turquoise-mandrill
  QC.Uni:
    repos:
      github.com/matbun/mlpf-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.homely-bronze-spider.sh
        container: qc.uni_sleazy-chartreuse-armadillo
  QC.Ver:
    repos:
      github.com/matbun/mlpf-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-xanthic-llama.sh
        container: qc.ver_clammy-alizarin-dhole
timeout: 5400
