config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/matbun/mlpf-itwinai-plugin:
      branch: main
      repo: https://github.com/matbun/mlpf-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/matbun/mlpf-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-xanthic-shark.sh
        container: qc.acc_wiggy-sangria-dogfish
  QC.Doc:
    repos:
      github.com/matbun/mlpf-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-yellow-coral.sh
        container: qc.doc_tasty-crimson-gorilla
      github.com/matbun/mlpf-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cyan-chimpanzee.sh
        container: qc.doc_cheeky-malachite-beagle
      github.com/matbun/mlpf-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-taupe-cichlid.sh
        container: qc.doc_crappy-tangerine-argentino
  QC.Lic:
    repos:
      github.com/matbun/mlpf-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-flax-giraffe.sh
        container: qc.lic_sleepy-sangria-tamarin
  QC.Met:
    repos:
      github.com/matbun/mlpf-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ochre-chow.sh
        container: qc.met_cozy-cinnamon-blue
  QC.Sec:
    repos:
      github.com/matbun/mlpf-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-brass-worm.sh
        container: qc.sec_snappy-periwinkle-bulldog
  QC.Sty:
    repos:
      github.com/matbun/mlpf-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-beige-tzu.sh
        container: qc.sty_crabby-ruby-bulldog
      github.com/matbun/mlpf-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-seashell-caracal.sh
        container: qc.sty_skimpy-heliotrope-toucan
      github.com/matbun/mlpf-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-brass-orangutan.sh
        container: qc.sty_lanky-mauve-gopher
  QC.Uni:
    repos:
      github.com/matbun/mlpf-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-salmon-angelfish.sh
        container: qc.uni_droopy-vermilion-bulldog
  QC.Ver:
    repos:
      github.com/matbun/mlpf-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chestnut-sparrow.sh
        container: qc.ver_stuffy-orchid-chow
timeout: 5400
